/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TravelRouteImport } from './routes/travel'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as MerchRouteImport } from './routes/merch'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConsentRouteImport } from './routes/consent'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ArtistsRouteImport } from './routes/artists'
import { Route as AftercareRouteImport } from './routes/aftercare'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudioIndexRouteImport } from './routes/studio.index'
import { Route as StylesFineLineRouteImport } from './routes/styles.fine-line'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ArtistsSlugRouteImport } from './routes/artists.$slug'

const TravelRoute = TravelRouteImport.update({
  id: '/travel',
  path: '/travel',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchRoute = MerchRouteImport.update({
  id: '/merch',
  path: '/merch',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentRoute = ConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsRoute = ArtistsRouteImport.update({
  id: '/artists',
  path: '/artists',
  getParentRoute: () => rootRouteImport,
} as any)
const AftercareRoute = AftercareRouteImport.update({
  id: '/aftercare',
  path: '/aftercare',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioRoute,
} as any)
const StylesFineLineRoute = StylesFineLineRouteImport.update({
  id: '/styles/fine-line',
  path: '/styles/fine-line',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const ArtistsSlugRoute = ArtistsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ArtistsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aftercare': typeof AftercareRoute
  '/artists': typeof ArtistsRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/booking': typeof BookingRoute
  '/consent': typeof ConsentRoute
  '/contact': typeof ContactRoute
  '/merch': typeof MerchRoute
  '/portfolio': typeof PortfolioRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRouteWithChildren
  '/travel': typeof TravelRoute
  '/artists/$slug': typeof ArtistsSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/styles/fine-line': typeof StylesFineLineRoute
  '/studio/': typeof StudioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aftercare': typeof AftercareRoute
  '/artists': typeof ArtistsRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/booking': typeof BookingRoute
  '/consent': typeof ConsentRoute
  '/contact': typeof ContactRoute
  '/merch': typeof MerchRoute
  '/portfolio': typeof PortfolioRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/travel': typeof TravelRoute
  '/artists/$slug': typeof ArtistsSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/styles/fine-line': typeof StylesFineLineRoute
  '/studio': typeof StudioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aftercare': typeof AftercareRoute
  '/artists': typeof ArtistsRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/booking': typeof BookingRoute
  '/consent': typeof ConsentRoute
  '/contact': typeof ContactRoute
  '/merch': typeof MerchRoute
  '/portfolio': typeof PortfolioRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRouteWithChildren
  '/travel': typeof TravelRoute
  '/artists/$slug': typeof ArtistsSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/styles/fine-line': typeof StylesFineLineRoute
  '/studio/': typeof StudioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aftercare'
    | '/artists'
    | '/blog'
    | '/booking'
    | '/consent'
    | '/contact'
    | '/merch'
    | '/portfolio'
    | '/sitemap.xml'
    | '/studio'
    | '/travel'
    | '/artists/$slug'
    | '/blog/$slug'
    | '/styles/fine-line'
    | '/studio/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aftercare'
    | '/artists'
    | '/blog'
    | '/booking'
    | '/consent'
    | '/contact'
    | '/merch'
    | '/portfolio'
    | '/sitemap.xml'
    | '/travel'
    | '/artists/$slug'
    | '/blog/$slug'
    | '/styles/fine-line'
    | '/studio'
  id:
    | '__root__'
    | '/'
    | '/aftercare'
    | '/artists'
    | '/blog'
    | '/booking'
    | '/consent'
    | '/contact'
    | '/merch'
    | '/portfolio'
    | '/sitemap.xml'
    | '/studio'
    | '/travel'
    | '/artists/$slug'
    | '/blog/$slug'
    | '/styles/fine-line'
    | '/studio/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AftercareRoute: typeof AftercareRoute
  ArtistsRoute: typeof ArtistsRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  BookingRoute: typeof BookingRoute
  ConsentRoute: typeof ConsentRoute
  ContactRoute: typeof ContactRoute
  MerchRoute: typeof MerchRoute
  PortfolioRoute: typeof PortfolioRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StudioRoute: typeof StudioRouteWithChildren
  TravelRoute: typeof TravelRoute
  StylesFineLineRoute: typeof StylesFineLineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/travel': {
      id: '/travel'
      path: '/travel'
      fullPath: '/travel'
      preLoaderRoute: typeof TravelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merch': {
      id: '/merch'
      path: '/merch'
      fullPath: '/merch'
      preLoaderRoute: typeof MerchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent': {
      id: '/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof ConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists': {
      id: '/artists'
      path: '/artists'
      fullPath: '/artists'
      preLoaderRoute: typeof ArtistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aftercare': {
      id: '/aftercare'
      path: '/aftercare'
      fullPath: '/aftercare'
      preLoaderRoute: typeof AftercareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/': {
      id: '/studio/'
      path: '/'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof StudioRoute
    }
    '/styles/fine-line': {
      id: '/styles/fine-line'
      path: '/styles/fine-line'
      fullPath: '/styles/fine-line'
      preLoaderRoute: typeof StylesFineLineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/artists/$slug': {
      id: '/artists/$slug'
      path: '/$slug'
      fullPath: '/artists/$slug'
      preLoaderRoute: typeof ArtistsSlugRouteImport
      parentRoute: typeof ArtistsRoute
    }
  }
}

interface ArtistsRouteChildren {
  ArtistsSlugRoute: typeof ArtistsSlugRoute
}

const ArtistsRouteChildren: ArtistsRouteChildren = {
  ArtistsSlugRoute: ArtistsSlugRoute,
}

const ArtistsRouteWithChildren =
  ArtistsRoute._addFileChildren(ArtistsRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface StudioRouteChildren {
  StudioIndexRoute: typeof StudioIndexRoute
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioIndexRoute: StudioIndexRoute,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AftercareRoute: AftercareRoute,
  ArtistsRoute: ArtistsRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  BookingRoute: BookingRoute,
  ConsentRoute: ConsentRoute,
  ContactRoute: ContactRoute,
  MerchRoute: MerchRoute,
  PortfolioRoute: PortfolioRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StudioRoute: StudioRouteWithChildren,
  TravelRoute: TravelRoute,
  StylesFineLineRoute: StylesFineLineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
